version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: "ubuntu-lts-latest"
  tools:
    python: "miniforge3-latest"

conda:
  environment: docs/docs_env.yml

python:
  install:
    - method: pip
      path: .
